name: flutterbook
description: Welcome to the 4 in one application


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_core:
  scoped_model:
  path_provider:
  sqflite:
  flutter_slidable:
  intl:
  image_picker:
  flutter_calendar_carousel:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  